services:
  app-update:
    image: ghcr.io/frantjc/go-steamcmd/app-update
    entrypoint: app-update /root/steamapp
    build: .
    volumes:
      - ./hack:/root
  app-info-print:
    image: ghcr.io/frantjc/go-steamcmd/app-info-print
    entrypoint: app-info-print
    build: .
    volumes:
      - ./hack:/root
